LOG:  00000: statement: create function trap_matching_test(int) returns int as $$  declare x int;  sx smallint;  y int;  begin  begin -- start a subtransaction  x := 100 / $1;  sx := $1;  select into y unique1 from tenk1 where unique2 =  (select unique2 from tenk1 b where ten = $1);  exception  when data_exception then -- category match  raise notice 'caught data_exception';  x := -1;  when NUMERIC_VALUE_OUT_OF_RANGE OR CARDINALITY_VIOLATION then  raise notice 'caught numeric_value_out_of_range or cardinality_violation';  x := -2;  end;  return x;  end$$ language plpgsql;
LOCATION:  exec_simple_query, postgres.c:938
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
LOCATION:  exec_stmt_raise, pl_exec.c:3216
STATEMENT:  create function trap_matching_test(int) returns int as $$  declare x int;  sx smallint;  y int;  begin  begin -- start a subtransaction  x := 100 / $1;  sx := $1;  select into y unique1 from tenk1 where unique2 =  (select unique2 from tenk1 b where ten = $1);  exception  when data_exception then -- category match  raise notice 'caught data_exception';  x := -1;  when NUMERIC_VALUE_OUT_OF_RANGE OR CARDINALITY_VIOLATION then  raise notice 'caught numeric_value_out_of_range or cardinality_violation';  x := -2;  end;  return x;  end$$ language plpgsql;
ERROR:  42601: syntax error at end of input at character 535
LOCATION:  plpgsql_yyerror, pl_scanner.c:623
STATEMENT:  create function trap_matching_test(int) returns int as $$  declare x int;  sx smallint;  y int;  begin  begin -- start a subtransaction  x := 100 / $1;  sx := $1;  select into y unique1 from tenk1 where unique2 =  (select unique2 from tenk1 b where ten = $1);  exception  when data_exception then -- category match  raise notice 'caught data_exception';  x := -1;  when NUMERIC_VALUE_OUT_OF_RANGE OR CARDINALITY_VIOLATION then  raise notice 'caught numeric_value_out_of_range or cardinality_violation';  x := -2;  end;  return x;  end$$ language plpgsql;
