CREATE INDEX fooi ON foo (f1);
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE INDEX
ERROR:  42P01: relation "foo" does not exist
